services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://collabamap:collabamap@mongodb:27017
    restart: unless-stopped
    volumes:
      - ./app:/app/app
      - ./pyproject.toml:/app/pyproject.toml
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /app/app
        - action: sync+restart
          path: ./frontend
          target: /app/frontend
    networks:
      - collabamap-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=collabamap
      - MONGO_INITDB_ROOT_PASSWORD=collabamap
    restart: unless-stopped
    networks:
      - collabamap-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=collabamap
      - ME_CONFIG_MONGODB_ADMINPASSWORD=collabamap
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_URL=mongodb://collabamap:collabamap@mongodb:27017/
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - collabamap-network

networks:
  collabamap-network:
    driver: bridge

volumes:
  mongodb_data: