[project]
name = "collabamap"
version = "0.1.0"
description = "its a map that collaborates"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beanie>=1.29.0",
    "fastapi>=0.115.12",
    "fastapi-cors>=0.0.6",
    "openai>=1.69.0",
    "pillow>=11.1.0",
]
